### PR TITLE
added bootstrap

### PR DESCRIPTION
**Pull request by jasonmullins**

### CODE REVIEW

**Comment by dspencer999** [comment]
Why is there a node server? I thought we we're going to use Jetty and Jboss' jax-rs implementation on the back end. And standard maven directory structure for web apps

**Comment by jasonmullins** [comment]
There are a few reasons:
1. We need a proxy that can detect xsrf, but the api should not verify an xsrf token - this type of functionality should be owned by the proxy.
2. I'd like to keep the deployments totally separate - the front end should be built to be deployed to different locations than the back end - so, we need a proxy because browsers commonly block cross domain requests.
3. Pretty URLs for routes - /users/johndoe/photos instead of /singlepageapp.html#/users/johndoe/photos
4. I like using jade to build the html
5. As discussed, for the prototype, we can still put the node servers on the same machine as jetty - just use different ports.

Any other comments?

**Comment by dspencer999** [comment]
Sounds good Jason. Thanks for the explanation. No other comments at the moment

**Comment by krullshards** [comment]
Jade runs on node?  It looks like an alternate way to write HTML..  I'm not
quite sold on why it's better than just writing HTML directly.  Maybe you
can give us more detail?  I'm not saying not to use it, it's totally up to
you, I'm just trying to understand what it's all about.

Fahim, have you used Jade or node.js?

## 

_Kamran Shah_
CEO
_Myth Software_
(c) 703-623-8152
(o) 703-595-4764 x101
kamran.shah@mythsoftware.com

**Comment by jasonmullins** [comment]
I think Jade forces you to keep your markup cleaner, however that's not the main reason I like it.
I like it because of the templating features - layouts, blocks, includes, ifs, etc.

**Comment by krullshards** [comment]
I followed the instructions and had some issues running node.

## 

_Kamran Shah_
CEO
_Myth Software_
(c) 703-623-8152
(o) 703-595-4764 x101
kamran.shah@mythsoftware.com

**Pull request merged**
