### PR TITLE
B-01050/dockerize dockerized the project

### PR DESCRIPTION
**Pull request by jasonmullins**

### CODE REVIEW

**Comment by krullshards** [comment]
You dockerized it?  I thought Greg was doing that?  That was quick.

## 

_Kamran Shah_
CEO
_Myth Software_
(c) 703-623-8152
(o) 703-595-4764 x101
kamran.shah@mythsoftware.com

**Comment by jasonmullins** [comment]
Yeah, since I already knew the config stuff for node, I think it was easier for me just to do.  Really, all you do is translate the stuff you need to do into the docker file.

**Comment by jasonmullins** [comment]
I wasn't sure if Greg was working on that or Jenkins.  Anyway, when we start working on a story, we should pull it over to "In Progress" in V1.

**Comment by krullshards** [comment]
Agreed.  I don't know if anyone besides you, Do and me have logged into
there yet.

## 

_Kamran Shah_
CEO
_Myth Software_
(c) 703-623-8152
(o) 703-595-4764 x101
kamran.shah@mythsoftware.com

**Pull request merged**
